"""Rewrite lit RUN lines so they drive the SandboxVectorizer's LoadStoreVec.

Produces a unified diff by default (nothing in llvm-project is touched); with
--apply the edits are written in place so `llvm-lit` and
`utils/update_test_checks.py` can be run against them.
"""

from __future__ import annotations

import difflib
import os
import re
import subprocess

from .runline import LSV_PASS_NAME, SBVEC_PASS_NAME, RUN_RE

PASSES_TOKEN_RE = re.compile(
    r"(?P<flag>-{1,2}passes)(?P<sep>=|\s+)(?P<value>'[^']*'|\"[^\"]*\"|\S+)"
)


def rewrite_line(line: str, sbvec_flags: str) -> str | None:
    """Rewrite one physical RUN line; returns None if it needs no change."""
    if not RUN_RE.match(line) or LSV_PASS_NAME not in line:
        return None
    if "amdgpu-load-store-vectorizer" in line or "nvptx-load-store-vectorizer" in line:
        return None

    changed = False

    def sub(m: re.Match) -> str:
        nonlocal changed
        value = m.group("value")
        if LSV_PASS_NAME not in value:
            return m.group(0)
        changed = True
        new_value = value.replace(LSV_PASS_NAME, SBVEC_PASS_NAME)
        return f"{m.group('flag')}{m.group('sep')}{new_value} {sbvec_flags}"

    out = PASSES_TOKEN_RE.sub(sub, line)
    return out if changed else None


def rewrite_file(path: str, sbvec_flags: str) -> tuple[list[str], list[str]]:
    with open(path, "r", errors="replace") as f:
        original = f.read().splitlines(keepends=True)
    new = []
    for line in original:
        stripped = line.rstrip("\n")
        rewritten = rewrite_line(stripped, sbvec_flags)
        new.append(line if rewritten is None else rewritten + "\n")
    return original, new


def make_flags(pipeline: str, extra: list[str]) -> str:
    # The pipeline string contains '<' and '>' -- it must stay quoted or lit's
    # shell will treat them as redirections.
    return " ".join([f'-sbvec-passes="{pipeline}"', *extra])


def run_rewrite(
    tests: list[str],
    llvm_root: str,
    pipeline: str,
    extra_flags: list[str],
    apply: bool,
    patch_path: str | None,
) -> tuple[int, str]:
    flags = make_flags(pipeline, extra_flags)
    diff_chunks: list[str] = []
    changed = 0
    for path in tests:
        original, new = rewrite_file(path, flags)
        if original == new:
            continue
        changed += 1
        rel = os.path.relpath(path, llvm_root)
        diff_chunks.extend(
            difflib.unified_diff(
                original, new, fromfile=f"a/{rel}", tofile=f"b/{rel}"
            )
        )
        if apply:
            with open(path, "w") as f:
                f.writelines(new)
    patch = "".join(diff_chunks)
    if patch_path:
        with open(patch_path, "w") as f:
            f.write(patch)
    return changed, patch


def is_autogenerated(path: str) -> bool:
    with open(path, "r", errors="replace") as f:
        return "utils/update_test_checks.py" in f.read(4096)


def update_checks(
    tests: list[str], llvm_root: str, opt_binary: str
) -> tuple[list[str], list[str], list[str]]:
    """Regenerate autogenerated CHECK lines.

    Returns (updated, skipped-because-handwritten, failures).  Tests whose
    CHECK lines are hand-written cannot be regenerated -- they have to be
    triaged by reading the diff.
    """
    script = os.path.join(llvm_root, "llvm", "utils", "update_test_checks.py")
    updated, handwritten, failures = [], [], []
    for path in tests:
        rel = os.path.relpath(path, llvm_root)
        if not is_autogenerated(path):
            handwritten.append(rel)
            continue
        p = subprocess.run(
            ["python3", script, f"--opt-binary={opt_binary}", path],
            capture_output=True,
            text=True,
        )
        if p.returncode != 0:
            failures.append(f"{rel}: {p.stderr.strip()[:200]}")
        else:
            updated.append(rel)
    return updated, handwritten, failures
